name: integration tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipx install hatch

    - name: Test with Docker backend
      run: |
        hatch run proceed run tests/smoke_test.yaml --runner docker --args tmp=/tmp/docker

    - name: Test with Slurm backend (Slurm running locally via Docker Compose)
      run: |
        # Create a scratch directory to share with this script, docker compose, and slurm.
        # This is because the worker nodes in compose are running as root.
        mkdir -p /tmp/slurm/shared
        chmod a+w /tmp/slurm/shared

        # Stand up a local Slurm cluster, with enroot and pyxis for containers.
        # This takes a few minutes to do some Docker builds.
        git clone https://github.com/benjamin-heasly/slurm-docker-cluster.git
        cd slurm-docker-cluster
        make up

        # Add an "srun" wrapper script that forwards into the local scheduler container.
        cd ..
        export PATH=$PATH:$PWD/slurm-docker-cluster/bin

        # Use the slurm runner via, via the srun wrapper, into the Compose cluster.
        hatch run proceed run tests/smoke_test.yaml --runner slurm --args tmp=/tmp/slurm

        # Done with the local Slurm cluster.
        cd slurm-docker-cluster
        make down
        make clean
